<?php

namespace App\Http\Requests\MaintenanceRequests;

use Illuminate\Foundation\Http\FormRequest;

class AddReviewRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'rating' => 'required|numeric|between:1,5',
        ];
    }
    public function messages()
    {
        return [
            'rating.required' => 'Rating is required',
            'rating.between' => 'Rating must be between 1 and 5',
            'rating.numeric' => 'Rating must be a number',
        ]; // TODO: Change the autogenerated stub
    }
}
