<?php

namespace App\Http\Requests\MaintenanceRequests;

use Illuminate\Foundation\Http\FormRequest;

class StoringNewRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'unit_id' => ['required', 'exists:units,id'],
            'project_id' => ['required', 'exists:projects,id'],
            'date' => ['required', 'date'],
            'picture'   => ['nullable', 'image', 'mimes:jpeg,png,jpg,gif,svg'],
            'notes'     => ['nullable', 'string'],
            'time'      => ['required', 'string'],
        ];
    }
    public function messages()
    {
        return [
            'unit_id.required' => 'Unit field is required.',
            'project_id.required' => 'Project field is required.',
            'date.required' => 'Date field is required.',
            'picture.image' => 'Picture must be an image.',
            'time.required' => 'Time field is required.',
        ]; // TODO: Change the autogenerated stub
    }
}
